name: snow_aso
channels:
  - defaults
  - conda-forge
dependencies:
  - boost=1.66.0
  - boost-cpp=1.66.0
  - clangdev=6.0.1
  - flann=1.9.1
  - geotiff=1.4.2
  - giflib=5.1.4
  - hexer=1.4.0
  - json-c=0.13.1
  - laszip=3.2.2
  - laz-perf=1.1.0
  - libcxx=6.0.1
  - libflang=5.0.0
  - libgdal=2.2.4
  - llvm-meta=6.0.1
  - llvmdev=6.0.1
  - nitro=2.7.dev2
  - openblas=0.3.2
  - pcl=1.8.1
  - pdal=1.7.1
  - proj4=4.9.3
  - python-pdal=2.0.0
  - qt=5.6.2
  - blas=1.0
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.8.13
  - curl=7.61.0
  - cycler=0.10.0
  - expat=2.2.5
  - freetype=2.9.1
  - freexl=1.0.5
  - gdal=2.2.2
  - geos=3.6.2
  - hdf4=4.2.13
  - hdf5=1.10.1
  - icc_rt=2017.0.4
  - icu=58.2
  - intel-openmp=2018.0.3
  - jpeg=9b
  - jsoncpp=1.8.3
  - kealib=1.4.7
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.61.0
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.5.0
  - libpng=1.6.34
  - libpq=10.3
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - matplotlib=2.2.2
  - mkl=2018.0.3
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - numpy=1.15.0
  - numpy-base=1.15.0
  - openjpeg=2.3.0
  - openssl=1.0.2p
  - packaging=17.1
  - pandas=0.23.4
  - pcre=8.42
  - pip=10.0.1
  - pixman=0.34.0
  - postgresql=10.3
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - setuptools=40.0.0
  - sip=4.18.1
  - six=1.11.0
  - sqlite=3.20.1
  - tk=8.6.7
  - tornado=5.1
  - vc=14
  - vs2015_runtime=14.0.25123
  - wheel=0.31.1
  - wincertstore=0.2
  - xerces-c=3.2.0
  - xz=5.2.4
  - zlib=1.2.11
