name: snow_aso
channels:
  - conda-forge
  - defaults
dependencies:
  - boost-cpp
  - flann
  - hexer
  - jsoncpp
  - laszip
  - laz-perf
  - nitro
  - pcl
  - pdal
  - python-pdal
  - blas
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - curl
  - cycler
  - expat
  - fontconfig
  - freetype
  - freexl
  - gdal
  - geos
  - gettext
  - giflib
  - glib
  - hdf4
  - hdf5
  - icu
  - intel-openmp
  - jpeg
  - json-c
  - kealib
  - kiwisolver
  - libboost
  - libcurl
  - libcxx
  - libcxxabi
  - libdap4
  - libedit
  - libffi
  - libgcc
  - libgdal
  - libgfortran
  - libiconv
  - libkml
  - libnetcdf
  - libopenblas
  - libpng
  - libpq
  - libspatialite
  - libssh2
  - libtiff
  - libuuid
  - libxml2
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy
  - numpy-base
  - openblas
  - openblas-devel
  - openjpeg
  - openssl
  - packaging
  - pandas
  - patsy
  - pcre
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj4
  - pyparsing
  - python
  - python-dateutil
  - pytz
  - readline
  - scipy
  - setuptools
  - six
  - sqlite
  - statsmodels
  - tk
  - tornado
  - wheel
  - xerces-c
  - xz
  - zlib
