name: snow_aso
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - gdal=2.4
  - ipython
  - matplotlib
  - pandas
  - pillow
  - pdal=1.9
  - pip
  - python-pdal
  - statsmodels
  - pip:
      - opencv-python
