name: snow_aso
channels:
  - defaults
  - conda-forge
dependencies:
  - boost-cpp=1.66.0
  - flann=1.9.1
  - hexer=1.4.0
  - jsoncpp=1.8.1
  - laszip=3.2.2
  - laz-perf=1.2.0
  - nitro=2.7.dev2
  - pcl=1.8.1
  - pdal=1.7.2
  - blas=1.0
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.4.16
  - curl=7.60.0
  - expat=2.2.5
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - geos=3.6.2
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.56.1
  - hdf4=4.2.13
  - hdf5=1.10.1
  - icu=58.2
  - intel-openmp=2018.0.3
  - jpeg=9b
  - json-c=0.13.1
  - kealib=1.4.7
  - libboost=1.65.1
  - libcurl=7.60.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libdap4=3.19.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=4.8.5
  - libgdal=2.2.4
  - libgfortran=3.0.1
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.4.1.1
  - libopenblas=0.2.20
  - libpng=1.6.34
  - libpq=10.3
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxml2=2.9.8
  - mkl=2018.0.3
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.14.5
  - numpy-base=1.14.5
  - openblas=0.2.20
  - openblas-devel=0.2.20
  - openjpeg=2.3.0
  - openssl=1.0.2o
  - pandas=0.23.1
  - pcre=8.42
  - pip=10.0.1
  - pixman=0.34.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - postgresql=10.3
  - proj4=4.9.3
  - python=3.6.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - readline=7.0
  - setuptools=39.2.0
  - six=1.11.0
  - sqlite=3.23.1
  - tk=8.6.7
  - wheel=0.31.1
  - xerces-c=3.2.1
  - xz=5.2.4
  - zlib=1.2.11
