name: snow_aso
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - gdal
  - ipython
  - matplotlib
  - pandas
  - pillow
  - pdal
  - pip
  - python-pdal
  - statsmodels
  - pip:
      - opencv-python
